version: 2
jobs:
jobs:
  build: 
    machine: 
      image: circleci/classic:201708-01
      
    dependencies:
      override:
        - yarn
      cache_directories:
        - ~/.cache/yarn
      pre:
        - yarn global add now

    test:
      override:
        - yarn test

    deployment:
      development:
        branch: master
        commands:
          - now -t ${NOW_TOKEN}
          - now -t ${NOW_TOKEN} alias foo-dev
      production:
        branch: production
        commands:
          - now -t ${NOW_TOKEN}
          - now -t ${NOW_TOKEN} alias foo